#!/bin/sh

# Script para darle acceso al usuario al audio de baja latencia, además de
# añadirlo a los grupos: realtime, audio, video, optical y uucp
# - Invocado en /installer/stage3.sh

# Configurar el audio de baja latencia

if [ "$(id -u)" -eq 0 ]; then
	echo "Error: Este script no debe ejecutarse como root." >&2
	exit 1
fi

# Añadimos el usuario a los grupos desados
sudo usermod -aG realtime,audio,video,optical,uucp "$USER"

# Permite al usuario (en el grupo "audio") utilizar dispositivos de audio con
# prioridad elevada y acceso a recursos extendidos.
cat <<-EOF | sudo tee -a /etc/security/limits.conf
	    @audio - rtprio 95
	    @audio - memlock unlimited
	    $RUSER hard nofile 524288
EOF
