#!/bin/bash

[ "$(id -u)" -eq 0 ] && exit 1

[ ! -d "$HOME/.config/rc/runlevels/default" ] &&
	mkdir -p "$HOME/.config/rc/runlevels/default"
[ ! -d "$HOME/.config/rc/runlevels/shutdown" ] &&
	mkdir -p "$HOME/.config/rc/runlevels/shutdown"

# Activar servicio
service_add() {
	sudo rc-update add "$1" "$2"
}
# Activar servicio para el usuario
user_service_add() {
	SERVICE="$1"
	RUNLEVEL="$2"
	if [ -d /run/user/1000/ ]; then
		rc-update add "$SERVICE" "$RUNLEVEL" -U
	else
		ln -s "/etc/user/init.d/$SERVICE" \
			"$HOME/.config/rc/runlevels/$RUNLEVEL/$SERVICE"
	fi
}

[ "$(id -u)" -eq 0 ] && exit 1

SERVICES=(
	"elogind"
	"earlyoom"
	"tlp"
	"xdm"
	"syslog-ng"
)

USER_SERVICES=(
	"dbus"
	"pipewire"
	"pipewire-pulse"
	"wireplumber"
)

# Activar los servicios del sistema del runlevel default
for SERVICE in "${SERVICES[@]}"; do
	service_add "$SERVICE" "default"
done

# Activar los servicios del usuario del runlevel default
for USER_SERVICE in "${USER_SERVICES[@]}"; do
	user_service_add "$USER_SERVICE" "default"
done
