#!/bin/bash

source /etc/os-release

[ "$(id -u)" -eq 0 ] && exit 1

if [ "$ID" = "artix" ]; then
	[ ! -d "$HOME/.config/rc/runlevels/default" ] &&
		mkdir -p "$HOME/.config/rc/runlevels/default"
	[ ! -d "$HOME/.config/rc/runlevels/shutdown" ] &&
		mkdir -p "$HOME/.config/rc/runlevels/shutdown"
fi

# Activar servicio
service_add() {
	if [ "$ID" = "artix" ]; then
		sudo rc-update -q add "$1" "$2"
	elif [ "$ID" = "arch" ]; then
		if [ "$SERVICE" = "syslog-ng" ]; then
			sudo systemctl enable "${SERVICE}@default.service"
		else
			sudo systemctl enable "$SERVICE"
		fi
	fi
}
# Activar servicio para el usuario
user_service_add() {
	SERVICE="$1"
	RUNLEVEL="$2"
	if [ "$ID" = "artix" ]; then
		if [ -d /run/user/1000/ ]; then
			rc-update -q add "$SERVICE" "$RUNLEVEL" -U
		else
			ln -s "/etc/user/init.d/$SERVICE" \
				"$HOME/.config/rc/runlevels/$RUNLEVEL/$SERVICE"
		fi
	elif [ "$ID" = "arch" ]; then
		systemctl --user enable "$SERVICE"
	fi
}

[ "$(id -u)" -eq 0 ] && exit 1

SERVICES=(
	"earlyoom"
	"fwupd"
	"syslog-ng"
	"tlp"
	"xdm"
)

USER_SERVICES=(
	"pipewire"
	"pipewire-pulse"
	"wireplumber"
)

# Activar los servicios del sistema del runlevel default
for SERVICE in "${SERVICES[@]}"; do
	service_add "$SERVICE" default >/dev/null 2>&1
done

if [ "$ID" = "artix" ]; then
	service_add elogind default >/dev/null 2>&1
	service_add local default >/dev/null 2>&1
	service_add localmount default >/dev/null 2>&1
	service_add netmount default >/dev/null 2>&1
	user_service_add dbus default >/dev/null 2>&1
fi

# Activar los servicios del usuario del runlevel default
for USER_SERVICE in "${USER_SERVICES[@]}"; do
	user_service_add "$USER_SERVICE" default >/dev/null 2>&1
done
