#!/bin/bash

# Script para recompilar las aplicaciones suckless
# - Invocado por /update.sh

source /etc/os-release

[ "$(id -u)" -eq 0 ] && exit 1

########
# UDEV #
########

# Permitir a Steam controlar mandos de PlayStation 4
sudo cp -f "$HOME/.dotfiles/assets/system/udev/99-steam-controller-perms.rules" \
	/usr/lib/udev/rules.d/

# Permitir al usuario escanear redes Wi-Fi y cambiar ajustes de red
id -nG "$USER" | grep network -q || sudo usermod -aG network "$USER"
[ -e /sys/class/power_supply/BAT0 ] &&
	sudo cp -f "$HOME/.dotfiles/assets/system/udev/50-org.freedesktop.NetworkManager.rules" \
		/etc/polkit-1/rules.d/

#######
# X11 #
#######

# Permitir hacer clic pulsando el trackpad
[ -e /sys/class/power_supply/BAT0 ] &&
	sudo cp "$HOME/.dotfiles/assets/system/xorg/40-libinput.conf" \
		/etc/X11/xorg.conf.d/
# Instalar el xinitrc
sudo cp -f "$HOME/.dotfiles/assets/system/xorg/xinitrc" \
	/etc/X11/xinit/

################
# Aplicaciones #
################

# Configurar keepassxc para que siga el tema de QT (Si no está ya configurado)
if [ ! -f "$HOME/.config/keepassxc/keepassxc.ini" ]; then
	mkdir -p "$HOME/.config/keepassxc"
	cp "$HOME/.dotfiles/assets/configs/apps/keepassxc/keepassxc.ini" \
		"$HOME"/.config/keepassxc/
fi

#############
# Servicios #
#############

# xdm
sudo cp -f "$HOME/.dotfiles/assets/system/services/xdm/Xresources" \
	/etc/X11/xdm/
sudo cp -f "$HOME/.dotfiles/assets/system/services/xdm/Xsetup_0" \
	/etc/X11/xdm/
# syslog-ng
sudo cp -f "$HOME/.dotfiles/assets/system/services/syslog-ng/syslog-ng.conf" \
	/etc/syslog-ng/

# elogind
if [ "$ID" = "artix" ]; then
	sudo install -m 755 "$HOME/.dotfiles/assets/system/services/elogind/nm-restart" \
		/lib/elogind/system-sleep/
fi

##############
# Miscelánea #
##############

# Desactivar el altavoz del PC
echo "blacklist pcspkr" | sudo tee /etc/modprobe.d/nobeep.conf >/dev/null

# Suspender de forma automática cuando la batería cae por debajo del 10%
if [ "$ID" = "artix" ]; then
	if [ -e /sys/class/power_supply/BAT0 ]; then
		# Instalar los scripts y archivos del servicio de auto-suspensión
		sudo install -m 755 "$HOME/.dotfiles/assets/system/services/auto-suspend/openrc/auto-suspend-service" \
			/etc/init.d/auto-suspend
		sudo install -m 755 "$HOME/.dotfiles/assets/system/services/auto-suspend/openrc/auto-suspend" \
			/usr/local/bin/
		sudo install -m 755 "$HOME/.dotfiles/assets/system/services/auto-suspend/openrc/auto-suspend-loop" \
			/usr/local/bin/
		# Activar el servicio
		sudo rc-update add auto-suspend default >/dev/null
	fi
fi

# TODO Implementar autosuspensión para arch también
