#!/bin/bash

source /etc/os-release

# 27-05-2025
[ "$ID" = "artix" ] && [ -x /usr/lib/libllhttp.so.9.2 ] &&
	sudo ln -sf /usr/lib/libllhttp.so.9.2 /usr/lib/libllhttp.so.9.3

if [ "$ID" = "artix" ] && pacman -Q poppler >/dev/null; then
	if [ ! -L /usr/lib/libpoppler-cpp.so.1 ]; then
		sudo ln -s /usr/lib/libpoppler-cpp.so.2.0.0 /usr/lib/libpoppler-cpp.so.1
	fi
fi
