#!/bin/bash

# Script para recompilar las aplicaciones suckless
# - Invocado por /update.sh

# Se termina la ejecución de toda la tubería despúes del primer fallo
set -o pipefail

[ "$(id -u)" -eq 0 ] && exit 1

# Directorio base para las aplicaciones suckless
SUCKLESS_BASE="$HOME/.dotfiles/suckless"

# Función para compilar una aplicación suckless
compile_suckless_app() {
	local APP="$1"
	local SUCKLESS_DIR="$SUCKLESS_BASE/$APP"

	# Limpiar directorio
	sudo make clean --directory "$SUCKLESS_DIR" >/dev/null 2>&1 || return 1
	sudo make install --directory "$SUCKLESS_DIR" >/dev/null 2>&1
}

# Recompilar aplicaciones suckless
for APP in dmenu st; do
	compile_suckless_app "$APP" || echo "Error: Falló la compilación de $APP."
done
