#!/bin/bash
# Este archivo no se linkea, se instala con install -m 755
# Al hacer cambios no olvides volverlo a instalar con:
# sudo install -m 755 "$HOME/.dotfiles/assets/system/auto-suspend" /usr/local/bin/auto-suspend

# Verifica el nivel de batería
BATTERY_LEVEL=$(cat /sys/class/power_supply/BAT0/capacity)
BATTERY_STATUS=$(cat /sys/class/power_supply/BAT0/status)

if [ "$BATTERY_STATUS" = "Discharging" ] && [ "$BATTERY_LEVEL" -le 10 ]; then
	/usr/bin/systemctl suspend
fi
