#!/bin/sh

service_add() { # Activar servicio
	sudo rc-update add "$1" default
}
user_service_add() { # Activar servicio
	rc-update add "$1" default -U
}

# Activar servicios
service_add elogind
service_add earlyoom
service_add tlp
service_add xdm
service_add syslog-ng

user_service_add pipewire
user_service_add pipewire-pulse
user_service_add wireplumber
