#!/bin/sh

[ -f "$HOME/.config/Xresources" ] && xrdb "$HOME/.config/Xresources"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		# shellcheck source=/dev/null
		[ -x "$f" ] && "$f" &
	done
fi

# Como no podemos activar los servicios de usuario en el chroot lo hacemos
# antes de inciar el entorno gráfico por 1a vez.
if [ -f "$HOME/.firstrun" ]; then
	rm "$HOME/.firstrun"
	"$HOME"/.dotfiles/updater/conf-services
	sleep 5
fi

exec dbus-launch --sh-syntax --exit-with-session sh -c 'while true; do dwm; done'
